# Generated by Django 5.1.3 on 2024-11-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilio_modelis',
            options={'verbose_name': 'Automobilio modelis'},
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name': 'Automobilis'},
        ),
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Paslauga'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name': 'Uzsakymas'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymo_eilute',
            options={'verbose_name': 'Uzsakymo eilute'},
        ),
    ]
