# Generated by Django 5.1.3 on 2024-11-29 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=100, verbose_name='Marke')),
                ('modelis', models.CharField(max_length=100, verbose_name='Modelis')),
            ],
            options={
                'verbose_name': 'Automobilio modelis',
                'verbose_name_plural': 'Automobilio modeliai',
            },
        ),
        migrations.CreateModel(
            name='Busena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100, verbose_name='Būsena')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=500, verbose_name='Pavadinimas')),
                ('kaina', models.IntegerField(verbose_name='Kaina')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(max_length=100, verbose_name='Valstybinis Nr.')),
                ('vin_kodas', models.CharField(max_length=50, verbose_name='VIN kodas')),
                ('klientas', models.CharField(max_length=200, verbose_name='Klientas')),
                ('automobilio_modelis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.automobilio_modelis')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100, verbose_name='Data')),
                ('automobilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.automobilis')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoservice.busena')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymo_eilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.CharField(max_length=100, verbose_name='Kiekis')),
                ('paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.paslauga')),
                ('uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.uzsakymas')),
            ],
            options={
                'verbose_name': 'Užsakymo eilutė',
                'verbose_name_plural': 'Užsakymų eilutės',
            },
        ),
    ]
