# Generated by Django 5.1.3 on 2024-12-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0007_alter_busena_options_alter_uzsakymas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='valstybinis_nr',
            field=models.CharField(max_length=100, unique=True, verbose_name='Valstybinis Nr.'),
        ),
    ]
