# Generated by Django 5.1.3 on 2024-12-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_alter_automobilis_valstybinis_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='nuotrauka',
            field=models.ImageField(null=True, upload_to='automobiliai', verbose_name='Nuotrauka'),
        ),
    ]
