# Generated by Django 5.1.3 on 2024-12-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0009_automobilis_nuotrauka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='nuotrauka',
            field=models.ImageField(blank=True, null=True, upload_to='automobiliai', verbose_name='Nuotrauka'),
        ),
    ]
