# Generated by Django 5.1.3 on 2024-12-05 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0010_alter_automobilis_nuotrauka'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='terminas',
            field=models.DateField(blank=True, null=True, verbose_name='Bus prieinama'),
        ),
    ]
