# Generated by Django 5.1.3 on 2024-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0011_uzsakymas_reader_uzsakymas_terminas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='terminas',
            field=models.DateField(blank=True, null=True, verbose_name='Gržinti iki'),
        ),
    ]
