# Generated by Django 5.1.3 on 2024-12-05 19:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0012_alter_uzsakymas_terminas'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='description',
            field=tinymce.models.HTMLField(default='Sveiki!'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='terminas',
            field=models.DateField(blank=True, null=True, verbose_name='Grąžinti iki'),
        ),
    ]
