# Generated by Django 5.1.3 on 2024-12-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0016_alter_profilis_nuotrauka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilis',
            options={'verbose_name': 'Profilis', 'verbose_name_plural': 'Profiliai'},
        ),
    ]
